name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Set path
      run: echo "/protoc/bin:$GOPATH/bin" >> $GITHUB_PATH

    - name: Install system dependencies
      run: |
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        wget https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip
        sudo unzip protoc-3.11.4-linux-x86_64.zip -d /protoc
        go install github.com/golang/protobuf/protoc-gen-go@latest
        rm protoc-3.11.4-linux-x86_64.zip

    - name: Build protoc
      run: |
        cd grpc
        ./build_protoc.sh
        cd ..

    - name: Get packages
      run: go get -d -v ./... && go install -v ./...

    - name: Build gtuncli
      run: |
        mkdir build
        cd gtuncli && go build -o ../build/gtuncli gtuncli.go && cd ..
      
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: gtuncli
        path: build/gtuncli
